/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Laboratorio2;

/**
 *
 * @author sdsantos
 */
public class GUI extends javax.swing.JFrame {

    
    String columnNames[] = {"Codigo Estudiantil","Primer Apellido","Primer Nombre","Semestre en curso","N1","N2","N3","N4","N5"};
    String lista[][] = new String[100][columnNames.length];
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        panelFormulario = new javax.swing.JPanel();
        vertabla = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        tituloCodigo = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        tituloApellido = new javax.swing.JLabel();
        textoApellido = new javax.swing.JTextField();
        tituloNombre = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        tituloSemestre = new javax.swing.JLabel();
        textoSemestre = new javax.swing.JTextField();
        tituloNota1 = new javax.swing.JLabel();
        textoNota1 = new javax.swing.JTextField();
        tituloNota2 = new javax.swing.JLabel();
        textoNota2 = new javax.swing.JTextField();
        tituloNota3 = new javax.swing.JLabel();
        textoNota3 = new javax.swing.JTextField();
        tituloNota4 = new javax.swing.JLabel();
        textoNota4 = new javax.swing.JTextField();
        tituloNota5 = new javax.swing.JLabel();
        textoNota5 = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(102, 153, 255));

        panelFormulario.setBackground(new java.awt.Color(204, 204, 255));

        vertabla.setText("Ver tabla");
        vertabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertablaActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI Symbol", 1, 48)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("CENTRO MEDICO UNINORTE");

        tituloCodigo.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        tituloCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCodigo.setText("Codigo estudiantil:");

        textoCodigo.setForeground(new java.awt.Color(153, 153, 153));
        textoCodigo.setText("Ingrese su codigo estudiantil");
        textoCodigo.setToolTipText("");
        textoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCodigoActionPerformed(evt);
            }
        });

        tituloApellido.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        tituloApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloApellido.setText("Primer apellido:");

        textoApellido.setForeground(new java.awt.Color(153, 153, 153));
        textoApellido.setText("Ingrese su apellido");
        textoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApellidoActionPerformed(evt);
            }
        });

        tituloNombre.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        tituloNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloNombre.setText("Primer nombre:");

        textoNombre.setForeground(new java.awt.Color(153, 153, 153));
        textoNombre.setText("Ingrese su nombre ");

        tituloSemestre.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        tituloSemestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloSemestre.setText("Semestre:");

        textoSemestre.setForeground(new java.awt.Color(153, 153, 153));
        textoSemestre.setText("Ingrese su semestre");

        tituloNota1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        tituloNota1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloNota1.setText("Nota 1:");

        tituloNota2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        tituloNota2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloNota2.setText("Nota 2:");

        tituloNota3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        tituloNota3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloNota3.setText("Nota 3:");

        tituloNota4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        tituloNota4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloNota4.setText("Nota 4:");

        tituloNota5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        tituloNota5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloNota5.setText("Nota 5:");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laboratorio2/Logo-UNINORTE (1).png"))); // NOI18N

        javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
        panelFormulario.setLayout(panelFormularioLayout);
        panelFormularioLayout.setHorizontalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(imagen)
                        .addGap(120, 120, 120)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloSemestre)
                            .addGroup(panelFormularioLayout.createSequentialGroup()
                                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tituloCodigo)
                                        .addComponent(tituloApellido)
                                        .addComponent(tituloNombre))
                                    .addGroup(panelFormularioLayout.createSequentialGroup()
                                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tituloNota4)
                                            .addComponent(tituloNota1))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textoNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFormularioLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textoSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelFormularioLayout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tituloNota5)
                                            .addComponent(tituloNota2))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoNota5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelFormularioLayout.createSequentialGroup()
                                                .addComponent(textoNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)
                                                .addComponent(tituloNota3)
                                                .addGap(18, 18, 18)
                                                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(vertabla)
                                                    .addComponent(textoNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(titulo)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelFormularioLayout.setVerticalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCodigo)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloApellido)
                    .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNombre)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloSemestre)
                    .addComponent(textoSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNota1)
                    .addComponent(textoNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloNota2)
                    .addComponent(textoNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloNota3)
                    .addComponent(textoNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNota4)
                    .addComponent(textoNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloNota5)
                    .addComponent(textoNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioLayout.createSequentialGroup()
                        .addComponent(Guardar)
                        .addGap(70, 70, 70)
                        .addComponent(vertabla)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioLayout.createSequentialGroup()
                        .addComponent(imagen)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout fondoPanelLayout = new javax.swing.GroupLayout(fondoPanel);
        fondoPanel.setLayout(fondoPanelLayout);
        fondoPanelLayout.setHorizontalGroup(
            fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoPanelLayout.setVerticalGroup(
            fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vertablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertablaActionPerformed
        // TODO add your handling code here:
        MOSTRAR showme = new MOSTRAR ();
      
      showme.setVisible(true);
    }//GEN-LAST:event_vertablaActionPerformed

    private void textoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoApellidoActionPerformed

    private void textoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCodigoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JTextField textoApellido;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoNota1;
    private javax.swing.JTextField textoNota2;
    private javax.swing.JTextField textoNota3;
    private javax.swing.JTextField textoNota4;
    private javax.swing.JTextField textoNota5;
    private javax.swing.JTextField textoSemestre;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloApellido;
    private javax.swing.JLabel tituloCodigo;
    private javax.swing.JLabel tituloNombre;
    private javax.swing.JLabel tituloNota1;
    private javax.swing.JLabel tituloNota2;
    private javax.swing.JLabel tituloNota3;
    private javax.swing.JLabel tituloNota4;
    private javax.swing.JLabel tituloNota5;
    private javax.swing.JLabel tituloSemestre;
    private javax.swing.JButton vertabla;
    // End of variables declaration//GEN-END:variables
}
